title: esviji, a free puzzle game on the Web and mobile devices
email: contact@esviji.com
description: > # this means to ignore newlines until "baseurl:"
  esviji is a free puzzle game that can be played in any browser (but not IE/Edge) on mobile and desktop.
baseurl: ""
url: "http://esviji.com"

permalink:           :year/:month/:title.html

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Social links.
twitter_username:     esviji
github_username:      esviji
facebook_username:    esviji

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  style: compressed
