title: esviji
email: contact@esviji.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://esviji.com"

permalink:           :year/:month/:title.html
relative_permalinks: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Social links.
twitter_username:     esviji
github_username:      esviji
facebook_username:    esviji

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  style: compressed
